[08-Oct-2018 19:40:01 Europe/Berlin]   Error    404 | not found    On File C:\xampp\htdocs\Core\Router.php  At Line 84   Stack Trace :  #0 C:\xampp\htdocs\public\index.php(57): Core\Router->dispatch('/')
#1 {main} 
[08-Oct-2018 19:40:01 Europe/Berlin]   Error    404 | not found    On File C:\xampp\htdocs\Core\Router.php  At Line 84   Stack Trace :  #0 C:\xampp\htdocs\public\index.php(57): Core\Router->dispatch('/robots.txt')
#1 {main} 
[08-Oct-2018 19:40:02 Europe/Berlin]   Error    404 | not found    On File C:\xampp\htdocs\Core\Router.php  At Line 84   Stack Trace :  #0 C:\xampp\htdocs\public\index.php(57): Core\Router->dispatch('/favicon.ico')
#1 {main} 
[08-Oct-2018 19:40:02 Europe/Berlin]   Error    404 | not found    On File C:\xampp\htdocs\Core\Router.php  At Line 84   Stack Trace :  #0 C:\xampp\htdocs\public\index.php(57): Core\Router->dispatch('/favicon.ico')
#1 {main} 
[08-Oct-2018 19:42:37 Europe/Berlin]   Error    404 | not found    On File C:\xampp\htdocs\Core\Router.php  At Line 84   Stack Trace :  #0 C:\xampp\htdocs\public\index.php(57): Core\Router->dispatch('/')
#1 {main} 
[08-Oct-2018 21:53:44 Europe/Berlin]   Error    Parse error: syntax error, unexpected ';', expecting ',' or ')' (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 26   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 21:54:35 Europe/Berlin]   Error    Parse error: syntax error, unexpected ';', expecting ',' or ')' (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 26   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 21:54:47 Europe/Berlin]   Error    Parse error: syntax error, unexpected ';', expecting ',' or ')' (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 26   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 22:00:01 Europe/Berlin]   Error    Parse error: syntax error, unexpected ';', expecting ',' or ')' (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 26   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 22:00:21 Europe/Berlin]   Error    Parse error: syntax error, unexpected ';', expecting ',' or ')' (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 26   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 22:00:23 Europe/Berlin]   Error    Parse error: syntax error, unexpected ';', expecting ',' or ')' (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 26   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 22:00:23 Europe/Berlin]   Error    404 | not found    On File C:\xampp\htdocs\Core\Router.php  At Line 84   Stack Trace :  #0 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/robots.txt')
#1 {main} 
[08-Oct-2018 22:00:29 Europe/Berlin]   Error    Parse error: syntax error, unexpected '$json_value' (T_VARIABLE), expecting ',' or ')' (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 27   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 22:02:04 Europe/Berlin]   Error    Parse error: syntax error, unexpected ';', expecting ',' or ')' (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 26   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 22:15:38 Europe/Berlin]   Error    Undefined variable: json (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 27   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 22:16:17 Europe/Berlin]   Error    Undefined variable: json (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 26   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 22:16:23 Europe/Berlin]   Error    Undefined variable: json (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 26   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 22:16:50 Europe/Berlin]   Error    Undefined variable: array (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 26   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 22:17:16 Europe/Berlin]   Error    Parse error: syntax error, unexpected 'print_r' (T_STRING), expecting ',' or ')' (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 26   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 22:17:33 Europe/Berlin]   Error    Parse error: syntax error, unexpected ';', expecting ',' or ')' (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 25   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
[08-Oct-2018 22:17:41 Europe/Berlin]   Error    htmlspecialchars() expects parameter 1 to be string, object given (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\vendor\illuminate\support\helpers.php  At Line 533   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(39): Core\Router->dispatch('/success')
#11 {main} 
